/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import Business.CaiDatBUS;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author cuhoa_000
 */
public class CaiDatGUI extends javax.swing.JPanel {

    /**
     * Creates new form CaiDatGUI
     */
    private String sLoaiNhanVien=null;
    private boolean OnOffAn=true;
    private boolean OnOffChuong=true;
    private String sMaLoaiChuong = null;
    public CaiDatGUI() {
        initComponents();
    }
    public CaiDatGUI(String sLoaiNhanVien) {
        initComponents();
        this.sLoaiNhanVien=sLoaiNhanVien;
        panelGioChoAn.setVisible(false);
        panelThemChuong.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbLogo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtGioiThieu = new javax.swing.JTextArea();
        lbThayDoiGCA = new javax.swing.JLabel();
        panelGioChoAn = new javax.swing.JPanel();
        lbGioChoAnHienTai = new javax.swing.JLabel();
        lbGio = new javax.swing.JLabel();
        lbGioChoAnHienTai1 = new javax.swing.JLabel();
        txtGioMoi = new javax.swing.JTextField();
        lbThayDoi = new javax.swing.JLabel();
        cbLoaiChuong1 = new javax.swing.JComboBox<>();
        lbGioChoAnHienTai3 = new javax.swing.JLabel();
        panelThemChuong = new javax.swing.JPanel();
        lbGioChoAnHienTai2 = new javax.swing.JLabel();
        lbThemChuong = new javax.swing.JLabel();
        cbLoaiChuong2 = new javax.swing.JComboBox<>();
        lbThemChuongPn = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Item/Untitled-1-03.png"))); // NOI18N
        add(lbLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 31, -1, -1));

        txtGioiThieu.setColumns(20);
        txtGioiThieu.setRows(5);
        txtGioiThieu.setText("   Đặt vấn đề \nHiện nay, với nhu cầu sử dụng thịt đặt biệt là thịt heo ở nước ta chưa hề giảm và vẫn đang tang cao. \nTuy nhiên, thị trường thịt ở trong nước chưa đảm bảo chất lượng. Nhận thấy điều đó, việc tạo ra hệ thống\nnuôi heo cho các nông trại để phát triển nông trại, quản lý cũng như  giảm thiệu các chi tiêu về lâu dài\ncho nông trại.\nCác trang trại hiện nay chủ yếu là quản lý một cách thủ công, phần lớn là theo dõi thủ công và ghi lại \nbằng giấy nên tốn rất nhiều thời gian và khó khăn trong việc giám giát.\nĐể giải quyết vấn đề trên, cần một giải pháp mang tính thực tiễn, cần xây dựng nên một hệ thống phục vụ \ncông tác quản lý heo. Để có thể theo sát, quản lý chuồng trại cũng như giám sát nhân viên.\n   Giải pháp\nMỗi con heo sẽ có thông tin như: mã số, mã số của cha mẹ, ngày sinh, tình trạng, cân nặng. Khi lợn con \nmới sinh sẽ được cấp thông tin. Lợn con đủ đủ điều kiện về cân nặng, ngày tuổi thì sẽ được tách đàn \nchuyển đến những chuồng nuôi chống. Đối với heo con được nhập từ cơ sở khác thì sẽ được chuyển đến \nnhững chuồng chống và được cấp mã và thông tin.\nMỗi chuồng nuôi sẽ có: mã chuồng nuôi, số lượng vật nuôi, số lượng vật nuôi tối đa, vị trí chuồng nuôi,\ntrình trạng chuồng nuôi. Chuồng nuôi sẽ nuôi những con heo cùng đàn (cùng cha me, cùng tuổi). Mỗi ngày\n nhân viên sẽ cho heo ăn theo từng khu theo công thức đã định sẵn phù hợp vối lứa tuổi. Trong thời \ngian chăm sóc nếu có nhu cầu chuyển truồng cho heo thì chỉ được chuyển heo tới chuồng chống. Khi heo \nbị bệnh nhân viên chuồng sẽ tiêm thuốc cho heo. Mỗi khi tiêm thuốc nhân viên cần in hoá đơn tiêm thuốc\n bao gồm các thông tin: mã thuốc, tên loại thuốc, số lượng, ngày tồn dư thuốc, giá.\nMỗi lứa tuổi heo thì sẽ có công thức cho ăn khác nhau. Mỗi công thức cho ăn sẽ có thông tin: tuổi nhỏ nhất, tuổi lớn nhất, mã loại thức ăn, số lượng(kg).\n");
        jScrollPane1.setViewportView(txtGioiThieu);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 31, 838, 300));

        lbThayDoiGCA.setBackground(new java.awt.Color(0, 153, 102));
        lbThayDoiGCA.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbThayDoiGCA.setForeground(new java.awt.Color(255, 255, 255));
        lbThayDoiGCA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbThayDoiGCA.setText("THAY ĐỔI GIỜ CHO ĂN");
        lbThayDoiGCA.setOpaque(true);
        lbThayDoiGCA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbThayDoiGCAMouseClicked(evt);
            }
        });
        add(lbThayDoiGCA, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 177, 22));

        panelGioChoAn.setBackground(new java.awt.Color(255, 255, 255));
        panelGioChoAn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbGioChoAnHienTai.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbGioChoAnHienTai.setForeground(new java.awt.Color(0, 153, 102));
        lbGioChoAnHienTai.setText("Giờ cho ăn hiện tại:");
        panelGioChoAn.add(lbGioChoAnHienTai, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        lbGio.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbGio.setForeground(new java.awt.Color(0, 153, 102));
        lbGio.setText("Gio");
        panelGioChoAn.add(lbGio, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, -1, -1));

        lbGioChoAnHienTai1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbGioChoAnHienTai1.setForeground(new java.awt.Color(0, 153, 102));
        lbGioChoAnHienTai1.setText("Giờ cho ăn mới:");
        panelGioChoAn.add(lbGioChoAnHienTai1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, -1, -1));

        txtGioMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGioMoiActionPerformed(evt);
            }
        });
        panelGioChoAn.add(txtGioMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 80, -1));

        lbThayDoi.setBackground(new java.awt.Color(0, 153, 102));
        lbThayDoi.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbThayDoi.setForeground(new java.awt.Color(255, 255, 255));
        lbThayDoi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbThayDoi.setText("THAY ĐỔI");
        lbThayDoi.setOpaque(true);
        lbThayDoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbThayDoiMouseClicked(evt);
            }
        });
        panelGioChoAn.add(lbThayDoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 177, 22));

        cbLoaiChuong1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chuồng heo nái mang thai", "Chuồng heo nái đẻ con", "Chuồng heo đực giống", "Chuồng heo chờ phối giống", "Chuồng heo thịt" }));
        cbLoaiChuong1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbLoaiChuong1MouseClicked(evt);
            }
        });
        panelGioChoAn.add(cbLoaiChuong1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 180, -1));

        lbGioChoAnHienTai3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbGioChoAnHienTai3.setForeground(new java.awt.Color(0, 153, 102));
        lbGioChoAnHienTai3.setText("Loại chuồng:");
        panelGioChoAn.add(lbGioChoAnHienTai3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        add(panelGioChoAn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 349, 838, 40));

        panelThemChuong.setBackground(new java.awt.Color(255, 255, 255));

        lbGioChoAnHienTai2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbGioChoAnHienTai2.setForeground(new java.awt.Color(0, 153, 102));
        lbGioChoAnHienTai2.setText("Loại chuồng:");

        lbThemChuong.setBackground(new java.awt.Color(0, 153, 102));
        lbThemChuong.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbThemChuong.setForeground(new java.awt.Color(255, 255, 255));
        lbThemChuong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbThemChuong.setText("THÊM CHUỒNG");
        lbThemChuong.setOpaque(true);
        lbThemChuong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbThemChuongMouseClicked(evt);
            }
        });

        cbLoaiChuong2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chuồng heo nái mang thai", "Chuồng heo nái đẻ con", "Chuồng heo đực giống", "Chuồng heo chờ phối giống", "Chuồng heo thịt" }));

        javax.swing.GroupLayout panelThemChuongLayout = new javax.swing.GroupLayout(panelThemChuong);
        panelThemChuong.setLayout(panelThemChuongLayout);
        panelThemChuongLayout.setHorizontalGroup(
            panelThemChuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelThemChuongLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbGioChoAnHienTai2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbLoaiChuong2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(lbThemChuong, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(349, Short.MAX_VALUE))
        );
        panelThemChuongLayout.setVerticalGroup(
            panelThemChuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelThemChuongLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelThemChuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbGioChoAnHienTai2)
                    .addComponent(lbThemChuong, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbLoaiChuong2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(panelThemChuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 393, 838, 40));

        lbThemChuongPn.setBackground(new java.awt.Color(0, 153, 102));
        lbThemChuongPn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbThemChuongPn.setForeground(new java.awt.Color(255, 255, 255));
        lbThemChuongPn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbThemChuongPn.setText("THÊM CHUỒNG");
        lbThemChuongPn.setOpaque(true);
        lbThemChuongPn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbThemChuongPnMouseClicked(evt);
            }
        });
        add(lbThemChuongPn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 177, 22));
    }// </editor-fold>//GEN-END:initComponents

    private void txtGioMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGioMoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGioMoiActionPerformed

    private void lbThayDoiGCAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbThayDoiGCAMouseClicked
        // TODO add your handling code here:
        panelGioChoAn.setVisible(OnOffChuong);
        if(OnOffChuong==true)
            this.OnOffChuong=false;
        else
            this.OnOffChuong=true;
    }//GEN-LAST:event_lbThayDoiGCAMouseClicked

    private void lbThemChuongPnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbThemChuongPnMouseClicked
        // TODO add your handling code here:
         panelThemChuong.setVisible(OnOffAn);
        if(OnOffAn==true)
            this.OnOffAn=false;
        else
            this.OnOffAn=true;
    }//GEN-LAST:event_lbThemChuongPnMouseClicked

    private void cbLoaiChuong1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbLoaiChuong1MouseClicked
        int iIndex=cbLoaiChuong1.getSelectedIndex();
        CaiDatBUS objCD=new CaiDatBUS();
        
        switch(iIndex)
        {
            case 0: 
                sMaLoaiChuong="LC02";
                break;
            case 1:
                sMaLoaiChuong="LC01";
                break;
            case 2:
                sMaLoaiChuong="LC04";
                break;
            case 3:
                sMaLoaiChuong="LC03";
                break;
            case 4:
                sMaLoaiChuong="LC05";
                break;
            default:
                break;
        }
        lbGio.setText(objCD.GioChoAn(sMaLoaiChuong));
    }//GEN-LAST:event_cbLoaiChuong1MouseClicked

    private void lbThayDoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbThayDoiMouseClicked
        // TODO add your handling code here:
        CaiDatBUS objCD=new CaiDatBUS();
        try {
            if(objCD.UpdateGioChoAn(txtGioMoi.getText(), sMaLoaiChuong))
            {
                JOptionPane.showMessageDialog(this, "Thay đổi giờ cho ăn thành công!", "THÔNG BÁO", JOptionPane.DEFAULT_OPTION);
            }
            else
                JOptionPane.showMessageDialog(this, "Có lỗi trong quá trình thay đổi!", "THÔNG BÁO", JOptionPane.WARNING_MESSAGE);
        } catch (SQLException ex) {
            Logger.getLogger(CaiDatGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lbThayDoiMouseClicked

    private void lbThemChuongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbThemChuongMouseClicked
        // TODO add your handling code here:
        int iIndex=cbLoaiChuong1.getSelectedIndex();
        CaiDatBUS objCD=new CaiDatBUS();
        String sMaThemLoaiChuong=null;
        switch(iIndex)
        {
            case 0: 
                sMaThemLoaiChuong="LC02";
                break;
            case 1:
                sMaThemLoaiChuong="LC01";
                break;
            case 2:
                sMaThemLoaiChuong="LC04";
                break;
            case 3:
                sMaThemLoaiChuong="LC03";
                break;
            case 4:
                sMaThemLoaiChuong="LC05";
                break;
            default:
                break;
        }
        try {
            if(objCD.InsertChuong(sMaThemLoaiChuong))
            {
                JOptionPane.showMessageDialog(this, "Thêm chuồng thành công!", "THÔNG BÁO", JOptionPane.DEFAULT_OPTION);
            }
            else
                JOptionPane.showMessageDialog(this, "Có lỗi trong quá trình thêm!", "THÔNG BÁO", JOptionPane.WARNING_MESSAGE);
        } catch (SQLException ex) {
            Logger.getLogger(CaiDatGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lbThemChuongMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbLoaiChuong1;
    private javax.swing.JComboBox<String> cbLoaiChuong2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbGio;
    private javax.swing.JLabel lbGioChoAnHienTai;
    private javax.swing.JLabel lbGioChoAnHienTai1;
    private javax.swing.JLabel lbGioChoAnHienTai2;
    private javax.swing.JLabel lbGioChoAnHienTai3;
    private javax.swing.JLabel lbLogo;
    private javax.swing.JLabel lbThayDoi;
    private javax.swing.JLabel lbThayDoiGCA;
    private javax.swing.JLabel lbThemChuong;
    private javax.swing.JLabel lbThemChuongPn;
    private javax.swing.JPanel panelGioChoAn;
    private javax.swing.JPanel panelThemChuong;
    private javax.swing.JTextField txtGioMoi;
    private javax.swing.JTextArea txtGioiThieu;
    // End of variables declaration//GEN-END:variables
}
