/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import Business.ChoAnBUS;
import java.util.ArrayList;
import Element.ThucAnELE;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;

public class ChoAnGUI extends javax.swing.JFrame {

    /**
     * Creates new form ChoAnGUI
     */
    ArrayList <ThucAnELE> lstThucAn=new ArrayList();
    ArrayList <String> lsCongThucAn=new ArrayList();
    ArrayList <Integer> lstTonKho=new ArrayList();
    private boolean bCheckTA=true;
    
    private static ChoAnGUI obj=null;
    public static ChoAnGUI getObj(String idMaChuong,String idLoaiChuong,String idMaNhanVien)
    {
        if(obj==null)
        {
            obj=new ChoAnGUI(idMaChuong,idLoaiChuong,idMaNhanVien);
        }
        return obj;
    }
    public ChoAnGUI() {
        initComponents();
        ShowThucAn();
    }
      public ChoAnGUI(String idMaChuong,String idLoaiChuong,String idMaNhanVien) {
        initComponents();
        txtMaChuong.setText(idMaChuong);
        txtLoaiChuong.setText(idLoaiChuong);
        txtNhanVien.setText(idMaNhanVien);
        ShowThucAn();
    }
    
    
    private void ShowThucAn()
    {
        
        cbTenCongThucAn.removeAllItems();
        lsCongThucAn.clear();
        ChoAnBUS objCA=new ChoAnBUS();
        ResultSet rs=objCA.GetCongThucAn("LC01");
        try
        {
            while(rs.next())
            {
                cbTenCongThucAn.addItem(rs.getString("TenCongThuc"));
                lsCongThucAn.add(rs.getString("MaCongThuc"));
                
            }
        }
        catch(SQLException exc)
        {
            System.out.println("Loi o showCbCongThucAn ChoAnGUi "+exc);
        }
        ResultSet rsTA= objCA.getThucAn();
        DefaultTableModel model;
        model = (DefaultTableModel) tableThucAnTrongKho.getModel();
        model.getDataVector().removeAllElements();
        int iStt=1;
        try
        {
            while(rsTA.next())
            {
               
                Vector vector =new Vector();
                vector.add (iStt);
                iStt++;
                vector.add(rsTA.getString("MaThucAn"));
                vector.add(rsTA.getString("TenThucAn"));
                vector.add(rsTA.getString("TonKho"));
                vector.add(rsTA.getString("DonViTinh"));
                vector.add(rsTA.getString("MaLoaiHang"));
                model.addRow(vector);
                
            }
        }
        catch(SQLException exc)
        {
            System.out.println("Loi o showCbCongThucAn ChoAn GUi" +exc);
        }
        
    }
    private void ShowTableCongThucAn()
    {
       
        String sIdCongThuc=lsCongThucAn.get(cbTenCongThucAn.getSelectedIndex());
        lstTonKho.clear();
        //System.out.println(sIdCongThuc);
        ChoAnBUS objCA=new ChoAnBUS();
        ResultSet rs=objCA.getThanhPhanTA(sIdCongThuc);
         DefaultTableModel model;
            model = (DefaultTableModel) tableCongThucAn.getModel();
            
            model.getDataVector().removeAllElements();
            model.fireTableDataChanged();
           int iStt=1;
           int iSoLuong=0,iTonKho=0;
         try
         {
             while(rs.next())
             {
                 Vector vector=new Vector();
                 vector.add(iStt);
                 iStt++;
                 vector.add(rs.getString("MaThucAn"));
                 vector.add(rs.getString("TenThucAn"));
                 vector.add(rs.getString("SoLuong"));
                 iSoLuong=Integer.parseInt(rs.getString("SoLuong"));
                 iTonKho=Integer.parseInt(rs.getString("TonKho"));
                 lstTonKho.add(iTonKho);
                 if(iTonKho-iSoLuong<0)
                     bCheckTA=false;
                 model.addRow(vector);
             }
         }
         catch(SQLException exc)
         {
             System.out.println("Loi o ShowTableCongThucAn ChoAnGUI "+exc);
         }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChoAn = new com.toedter.calendar.JDateChooser();
        lbLoaiChuong = new javax.swing.JLabel();
        txtLoaiChuong = new javax.swing.JTextField();
        lbMaChuong = new javax.swing.JLabel();
        txtMaChuong = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCongThucAn = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableThucAnTrongKho = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableDanhSachThucAn = new javax.swing.JTable();
        lbNhanVien = new javax.swing.JLabel();
        txtNhanVien = new javax.swing.JTextField();
        lbCongThucAn = new javax.swing.JLabel();
        cbTenCongThucAn = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnChuyen = new javax.swing.JToggleButton();
        btnChuyenHet = new javax.swing.JToggleButton();
        btnXacNhan = new javax.swing.JToggleButton();
        btnXoa = new javax.swing.JToggleButton();
        btnXoaHet = new javax.swing.JToggleButton();
        lbDanhSachThucAn = new javax.swing.JLabel();
        btnChinhSua = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cho Ăn");

        dateChoAn.setDateFormatString("yyyy-MM-dd\n");

        lbLoaiChuong.setText("Loại Chuồng");

        txtLoaiChuong.setText("jTextField1");

        lbMaChuong.setText("Mã Chuồng");

        txtMaChuong.setText("jTextField2");

        tableCongThucAn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "1", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableCongThucAn);

        tableThucAnTrongKho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableThucAnTrongKho.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        jScrollPane2.setViewportView(tableThucAnTrongKho);

        tableDanhSachThucAn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "STT", "Mã Thức Ăn", "Tên Thức Ăn", "Số Lượng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tableDanhSachThucAn);

        lbNhanVien.setText("Nhân Viên:");

        txtNhanVien.setText("jTextField3");

        lbCongThucAn.setText("Công thức ăn:");

        cbTenCongThucAn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbTenCongThucAn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbTenCongThucAnMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cbTenCongThucAnMousePressed(evt);
            }
        });
        cbTenCongThucAn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTenCongThucAnActionPerformed(evt);
            }
        });

        jLabel5.setText("Thức ăn trong kho");

        jLabel6.setText("Tìm");

        btnChuyen.setText("CH");
        btnChuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChuyenActionPerformed(evt);
            }
        });

        btnChuyenHet.setText("CH");
        btnChuyenHet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChuyenHetActionPerformed(evt);
            }
        });

        btnXacNhan.setText("Xác nhận");
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnXoaHet.setText("Xóa hết");
        btnXoaHet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaHetActionPerformed(evt);
            }
        });

        lbDanhSachThucAn.setText("Danh sách thức ăn");

        btnChinhSua.setText("Chỉnh sữa");
        btnChinhSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChinhSuaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnXacNhan)
                        .addGap(73, 73, 73)
                        .addComponent(btnXoa)
                        .addGap(18, 18, 18)
                        .addComponent(btnXoaHet)
                        .addGap(18, 18, 18)
                        .addComponent(btnChinhSua)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbLoaiChuong)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtLoaiChuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(211, 211, 211))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbNhanVien)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(212, 212, 212)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbMaChuong)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMaChuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(dateChoAn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(58, 58, 58)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 169, Short.MAX_VALUE)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(37, 37, 37))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnChuyenHet)
                                    .addComponent(btnChuyen)))
                            .addComponent(lbDanhSachThucAn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbCongThucAn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbTenCongThucAn, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtLoaiChuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbLoaiChuong))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtMaChuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbMaChuong)))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateChoAn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbNhanVien)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbCongThucAn)
                        .addComponent(lbDanhSachThucAn))
                    .addComponent(cbTenCongThucAn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(btnChuyenHet, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(btnChuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane3))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXacNhan)
                    .addComponent(btnXoa)
                    .addComponent(btnXoaHet)
                    .addComponent(btnChinhSua))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbTenCongThucAnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTenCongThucAnActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_cbTenCongThucAnActionPerformed

    private void cbTenCongThucAnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbTenCongThucAnMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cbTenCongThucAnMouseClicked

    private void cbTenCongThucAnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbTenCongThucAnMousePressed
        // TODO add your handling code here:
        ShowTableCongThucAn();
    }//GEN-LAST:event_cbTenCongThucAnMousePressed

    private void btnChuyenHetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChuyenHetActionPerformed
        // TODO add your handling code here:
        if(bCheckTA==false)
            JOptionPane.showMessageDialog(this, "Số Thức ăn trong kho không đủ!", "Không được!", JOptionPane.ERROR_MESSAGE);
        else
        {
            DefaultTableModel model;
            model = (DefaultTableModel) tableDanhSachThucAn.getModel();
            model.getDataVector().removeAllElements();
            model.fireTableDataChanged();
            for(int i=0;i<tableCongThucAn.getColumnCount();i++)
            {
                Vector vector=new Vector();
                vector.add(tableCongThucAn.getValueAt(i, 0));
                vector.add(tableCongThucAn.getValueAt(i, 1));
                vector.add(tableCongThucAn.getValueAt(i, 2));
                vector.add(tableCongThucAn.getValueAt(i, 3));
                model.addRow(vector);
            }
           
        }
    }//GEN-LAST:event_btnChuyenHetActionPerformed

    private void btnChuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChuyenActionPerformed
        // TODO add your handling code here:
        lstTonKho.clear();
        TableModel model1=    tableThucAnTrongKho.getModel();
        int [] indexs=tableThucAnTrongKho.getSelectedRows();
        
        DefaultTableModel model2=(DefaultTableModel) tableDanhSachThucAn.getModel();
        model2.getDataVector().removeAllElements();
        model2.fireTableDataChanged();
        for(int i=0;i<indexs.length;i++)
        {
            Object[] row=new Object[4];
            row[0]=i+1;
            row[1]=model1.getValueAt(indexs[i], 1);
            row[2]=model1.getValueAt(indexs[i], 2);
            row[3]=model1.getValueAt(indexs[i], 3);
            int iTonKho =Integer.parseInt(model1.getValueAt(indexs[i], 3).toString());
            lstTonKho.add(iTonKho);
            
            model2.addRow(row);
        }
        
    }//GEN-LAST:event_btnChuyenActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int iTest=tableDanhSachThucAn.getSelectedRow();
        lstTonKho.remove(iTest);
        
        ((DefaultTableModel)tableDanhSachThucAn.getModel()).removeRow(tableDanhSachThucAn.getSelectedRow());
        
        
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnXoaHetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaHetActionPerformed
        // TODO add your handling code here:
         DefaultTableModel model;
            model = (DefaultTableModel) tableDanhSachThucAn.getModel();
            model.getDataVector().removeAllElements();
            model.fireTableDataChanged();
    }//GEN-LAST:event_btnXoaHetActionPerformed
    
    
    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
         
        ChoAnBUS objCA=new ChoAnBUS();
        int n=tableDanhSachThucAn.getRowCount();
        String sDate=((JTextField)dateChoAn.getDateEditor().getUiComponent()).getText();
        
       
        int iCheck=0;
        String iMaLoaiChuong=txtLoaiChuong.getText();
        String iMaChuong=txtMaChuong.getText();
        String iMaNhanVien=txtNhanVien.getText();
        try
        {
        if(objCA.InsertPhieuXuatTA(sDate, iMaNhanVien, iMaChuong))
            for(int i=0;i<n;i++)
            {
                try
                {
                    String sMaThucAn=tableDanhSachThucAn.getModel()
                            .getValueAt(i, 1).toString();
                    int iSoLuong=Integer.parseInt(tableDanhSachThucAn.getModel()
                            .getValueAt(i, 3).toString());
                    int iConLai=lstTonKho.get(i)-iSoLuong;
                    String sIdPhieuXuat=objCA.getIDPhieuXuatTA();
                        if(objCA.InsertChiTietPhieuXuatTA(sMaThucAn, sIdPhieuXuat, iSoLuong))
                            if(objCA.UpdateThucAn(iConLai, sMaThucAn))
                                iCheck++;
                }
                catch(SQLException exc)
                {
                    System.out.println(" loi o btnXacNhan ChoAnGUI "+exc);
                }

            }
              
        }
        catch(SQLException exc)
        {
            System.out.println(" loi o btnXacNhan ChoAnGUI "+exc);

        }
           if(iCheck==n)
                 JOptionPane.showMessageDialog(null, "Cho ăn thành công",
                  "THÔNG BÁO", JOptionPane.INFORMATION_MESSAGE);
            else
             JOptionPane.showMessageDialog(null, "Có lỗi trong quá trình cho ăn",
                  "THÔNG BÁO", JOptionPane.WARNING_MESSAGE);
        
       
    }//GEN-LAST:event_btnXacNhanActionPerformed

    private void btnChinhSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChinhSuaActionPerformed
        // TODO add your handling code here:
        for (int i=0;i<lstTonKho.size();i++)
        {
            System.out.println(lstTonKho.get(i));
        }
    }//GEN-LAST:event_btnChinhSuaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChoAnGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChoAnGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChoAnGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChoAnGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChoAnGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnChinhSua;
    private javax.swing.JToggleButton btnChuyen;
    private javax.swing.JToggleButton btnChuyenHet;
    private javax.swing.JToggleButton btnXacNhan;
    private javax.swing.JToggleButton btnXoa;
    private javax.swing.JToggleButton btnXoaHet;
    private javax.swing.JComboBox<String> cbTenCongThucAn;
    private com.toedter.calendar.JDateChooser dateChoAn;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel lbCongThucAn;
    private javax.swing.JLabel lbDanhSachThucAn;
    private javax.swing.JLabel lbLoaiChuong;
    private javax.swing.JLabel lbMaChuong;
    private javax.swing.JLabel lbNhanVien;
    private javax.swing.JTable tableCongThucAn;
    private javax.swing.JTable tableDanhSachThucAn;
    private javax.swing.JTable tableThucAnTrongKho;
    private javax.swing.JTextField txtLoaiChuong;
    private javax.swing.JTextField txtMaChuong;
    private javax.swing.JTextField txtNhanVien;
    // End of variables declaration//GEN-END:variables
}
