/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JPanel;
import Business.HeoBUS;
import java.sql.Array;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import Element.LoaiChuongELE;
import Element.ChuongELE;
import javax.swing.JFrame;
/**
 *
 * @author cuhoa_000
 */
public class HeoGUI extends javax.swing.JPanel {

    /**
     * Creates new form HeoGUI
     */
    
    ArrayList<LoaiChuongELE> lsLC=new ArrayList();
    ArrayList<ChuongELE> lsC=new ArrayList();
    public HeoGUI() {
        initComponents();
        showInfo();
        
    }
    private  void showInfo()
    {
        showMenuLoaiChuong();
        JtxtSoLuongChuong.setText(lsLC.get(0).getSoLuongChuong());
        JtxtSoLuongChuong1.setText(lsLC.get(1).getSoLuongChuong());
        JtxtSoLuongChuong2.setText(lsLC.get(2).getSoLuongChuong());
        JtxtSoLuongChuong3.setText(lsLC.get(3).getSoLuongChuong());
        
        jTxtSucChua.setText(lsLC.get(0).getQuiDinh());
        jTxtSucChua1.setText(lsLC.get(1).getQuiDinh());
        jTxtSucChua2.setText(lsLC.get(2).getQuiDinh());
        jTxtSucChua3.setText(lsLC.get(3).getQuiDinh());
        
    }
  
      private void showMenuLoaiChuong()
      {
          HeoBUS objHeo=new HeoBUS();
          ResultSet rs= objHeo.getLoaiChuong(); //loai Chuong
          
          int i=0;
          
          try
          {
              while(rs.next())
              {
                  int itemp=objHeo.getSoLuongChuong(rs.getString("MaLoaiChuong"));
                  LoaiChuongELE tempLC=new LoaiChuongELE(rs.getString("MaLoaiChuong"),rs.getString("TenLoaiChuong"),
                          rs.getInt("QuyDinhSoLuong"),itemp);              
                  lsLC.add(tempLC);
                  
                  
              }
          }
          catch(SQLException exc)
          {
              System.out.println(exc);
          }
       
      }
     
//      private void showMenuChuong()
//      {
//          HeoBUS objHeoBUS=new HeoBUS();
//          ResultSet rs=objHeoBUS.getChuong();
//          int i=0;
//          try
//          {
//          while(rs.next())
//          {
//              ChuongELE tempCH = new ChuongELE(rs.getString("MaChuong"),rs.getString("MaLoaiChuong"),rs.getInt("SoLuongHeoDangChua"));
//              lsC.add(tempCH);
//              ResultSet rsL=objHeoBUS.getLoaiChuong("LC01");
//              while(rsL.next())
//              {
//              
//              LoaiChuongELE tempLC=new LoaiChuongELE(rsL.getString("MaLoaiChuong"),rsL.getString("MaLoaiHeo"),rsL.getString("TenLoaiChuong"),rsL.getInt("QuyDinhSoLuong"));
//               
//              lsLC.add(tempLC);
//              }
//          }
//          }
//          catch(SQLException exc)
//          {
//              System.out.println(exc);
//          }
//         
//          
//         
//          String sSoLuong =Integer.toString(lsC.get(0).getSoLuongHeoDangChua());
//          JtxtSoLuongHeo.setText(sSoLuong);
//          String sSucChua= Integer.toString(lsLC.get(0).getQuiDinh());
//          jTxtSucChua.setText(sSucChua);
//          
//      }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenuLoaiChuong = new javax.swing.JPanel();
        jLbXemDanhSach = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableHeo = new javax.swing.JTable();
        jTxt_TimKiem = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableChuong = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLbThemHeo = new javax.swing.JLabel();
        jLbChoAn = new javax.swing.JLabel();
        lblAddPig = new javax.swing.JLabel();
        lblEat = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLbSoLuongHeo1 = new javax.swing.JLabel();
        JTxtTenChuong1 = new javax.swing.JTextField();
        JtxtSoLuongChuong1 = new javax.swing.JTextField();
        jLbSucChua1 = new javax.swing.JLabel();
        jTxtSucChua1 = new javax.swing.JTextField();
        panelMenuChuong = new javax.swing.JPanel();
        JTxtTenChuong0 = new javax.swing.JTextField();
        jLbSoLuongHeo = new javax.swing.JLabel();
        JtxtSoLuongChuong = new javax.swing.JTextField();
        jLbSucChua = new javax.swing.JLabel();
        jTxtSucChua = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLbSoLuongHeo2 = new javax.swing.JLabel();
        jLbSucChua2 = new javax.swing.JLabel();
        jTxtSucChua2 = new javax.swing.JTextField();
        JtxtSoLuongChuong2 = new javax.swing.JTextField();
        JTxtTenChuong2 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLbSucChua3 = new javax.swing.JLabel();
        jLbSoLuongHeo3 = new javax.swing.JLabel();
        jTxtSucChua3 = new javax.swing.JTextField();
        JtxtSoLuongChuong3 = new javax.swing.JTextField();
        JTxtTenChuong3 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLbSoLuongHeo4 = new javax.swing.JLabel();
        jLbSucChua4 = new javax.swing.JLabel();
        jTxtSucChua4 = new javax.swing.JTextField();
        JtxtSoLuongHeo4 = new javax.swing.JTextField();
        JTxtTenChuong4 = new javax.swing.JTextField();
        panelThongBao = new javax.swing.JPanel();

        setBackground(new java.awt.Color(235, 233, 233));

        panelMenuLoaiChuong.setBackground(new java.awt.Color(255, 255, 255));

        jLbXemDanhSach.setIcon(new javax.swing.ImageIcon("C:\\Users\\cuhoa_000\\Desktop\\img icon\\list.png")); // NOI18N
        jLbXemDanhSach.setToolTipText("Xem Danh Sách Heo");
        jLbXemDanhSach.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLbXemDanhSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLbXemDanhSachMouseClicked(evt);
            }
        });

        TableHeo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TableHeo);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Item/loupe.png"))); // NOI18N

        tableChuong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã Chuồng", "Số Lượng Heo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableChuong.setToolTipText("");
        tableChuong.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tableChuong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableChuongMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tableChuong);

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DANH SÁCH CHUỒNG");
        jLabel1.setOpaque(true);

        jLbThemHeo.setIcon(new javax.swing.ImageIcon("C:\\Users\\cuhoa_000\\Desktop\\img icon\\plus (1).png")); // NOI18N
        jLbThemHeo.setToolTipText("thêm heo");
        jLbThemHeo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLbChoAn.setIcon(new javax.swing.ImageIcon("C:\\Users\\cuhoa_000\\Desktop\\img icon\\restaurant.png")); // NOI18N
        jLbChoAn.setToolTipText("Cho Ăn");
        jLbChoAn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblAddPig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Item/plus (1).png"))); // NOI18N
        lblAddPig.setText("Thêm heo");
        lblAddPig.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAddPigMouseClicked(evt);
            }
        });

        lblEat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Item/restaurant.png"))); // NOI18N
        lblEat.setText("Cho Ăn");

        javax.swing.GroupLayout panelMenuLoaiChuongLayout = new javax.swing.GroupLayout(panelMenuLoaiChuong);
        panelMenuLoaiChuong.setLayout(panelMenuLoaiChuongLayout);
        panelMenuLoaiChuongLayout.setHorizontalGroup(
            panelMenuLoaiChuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLoaiChuongLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelMenuLoaiChuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMenuLoaiChuongLayout.createSequentialGroup()
                        .addComponent(lblAddPig)
                        .addGap(18, 18, 18)
                        .addComponent(lblEat)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelMenuLoaiChuongLayout.createSequentialGroup()
                        .addGroup(panelMenuLoaiChuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGroup(panelMenuLoaiChuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelMenuLoaiChuongLayout.createSequentialGroup()
                                .addGroup(panelMenuLoaiChuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelMenuLoaiChuongLayout.createSequentialGroup()
                                        .addGap(126, 126, 126)
                                        .addComponent(jTxt_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelMenuLoaiChuongLayout.createSequentialGroup()
                                        .addGap(70, 70, 70)
                                        .addComponent(jLbThemHeo)
                                        .addGap(10, 10, 10)
                                        .addComponent(jLbChoAn)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLbXemDanhSach)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(panelMenuLoaiChuongLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(24, Short.MAX_VALUE))))))
        );
        panelMenuLoaiChuongLayout.setVerticalGroup(
            panelMenuLoaiChuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLoaiChuongLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelMenuLoaiChuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelMenuLoaiChuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTxt_TimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelMenuLoaiChuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addGroup(panelMenuLoaiChuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddPig, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEat))
                .addGap(61, 61, 61)
                .addGroup(panelMenuLoaiChuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLbThemHeo)
                    .addComponent(jLbChoAn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLbXemDanhSach))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLbSoLuongHeo1.setText("Số Lượng Chuồng:");

        JTxtTenChuong1.setText("Chuồng nái chữa");

        JtxtSoLuongChuong1.setText("jTextField3");

        jLbSucChua1.setText("Sức chứa:");

        jTxtSucChua1.setText("jTextField5");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JTxtTenChuong1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLbSoLuongHeo1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(JtxtSoLuongChuong1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLbSucChua1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTxtSucChua1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(JTxtTenChuong1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbSoLuongHeo1)
                    .addComponent(JtxtSoLuongChuong1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbSucChua1)
                    .addComponent(jTxtSucChua1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelMenuChuong.setBackground(new java.awt.Color(255, 255, 255));
        panelMenuChuong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelMenuChuongMouseClicked(evt);
            }
        });

        JTxtTenChuong0.setText("Chuồng heo nái đẻ heo con");
        JTxtTenChuong0.setEnabled(false);
        JTxtTenChuong0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTxtTenChuong0ActionPerformed(evt);
            }
        });

        jLbSoLuongHeo.setText("Số Lượng Chuồng:");

        JtxtSoLuongChuong.setText("jTextField3");

        jLbSucChua.setText("Sức chứa:");

        jTxtSucChua.setText("jTextField5");

        javax.swing.GroupLayout panelMenuChuongLayout = new javax.swing.GroupLayout(panelMenuChuong);
        panelMenuChuong.setLayout(panelMenuChuongLayout);
        panelMenuChuongLayout.setHorizontalGroup(
            panelMenuChuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuChuongLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMenuChuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JTxtTenChuong0, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelMenuChuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(panelMenuChuongLayout.createSequentialGroup()
                            .addComponent(jLbSoLuongHeo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(JtxtSoLuongChuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuChuongLayout.createSequentialGroup()
                            .addComponent(jLbSucChua)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTxtSucChua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelMenuChuongLayout.setVerticalGroup(
            panelMenuChuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuChuongLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JTxtTenChuong0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelMenuChuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbSoLuongHeo)
                    .addComponent(JtxtSoLuongChuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMenuChuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbSucChua)
                    .addComponent(jTxtSucChua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLbSoLuongHeo2.setText("Số Lượng Chuồng:");

        jLbSucChua2.setText("Sức chứa:");

        jTxtSucChua2.setText("jTextField5");

        JtxtSoLuongChuong2.setText("jTextField3");

        JTxtTenChuong2.setText("Chuồng heo đực giống");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JTxtTenChuong2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLbSoLuongHeo2))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLbSucChua2)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtSucChua2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JtxtSoLuongChuong2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JTxtTenChuong2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbSoLuongHeo2)
                    .addComponent(JtxtSoLuongChuong2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbSucChua2)
                    .addComponent(jTxtSucChua2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLbSucChua3.setText("Sức chứa:");

        jLbSoLuongHeo3.setText("Số Lượng Chuồng:");

        jTxtSucChua3.setText("jTextField5");

        JtxtSoLuongChuong3.setText("jTextField3");

        JTxtTenChuong3.setText("Chuồng nái chờ phối");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLbSucChua3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTxtSucChua3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLbSoLuongHeo3)
                                .addGap(20, 20, 20)
                                .addComponent(JtxtSoLuongChuong3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(69, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(JTxtTenChuong3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JTxtTenChuong3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbSoLuongHeo3)
                    .addComponent(JtxtSoLuongChuong3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbSucChua3)
                    .addComponent(jTxtSucChua3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLbSoLuongHeo4.setText("Số Lượng Chuồng:");

        jLbSucChua4.setText("Sức chứa:");

        jTxtSucChua4.setText("jTextField5");

        JtxtSoLuongHeo4.setText("jTextField3");

        JTxtTenChuong4.setText("Chuồng heo thịt");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLbSoLuongHeo4)
                            .addComponent(jLbSucChua4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtSucChua4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JtxtSoLuongHeo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(JTxtTenChuong4, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JTxtTenChuong4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbSoLuongHeo4)
                    .addComponent(JtxtSoLuongHeo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbSucChua4)
                    .addComponent(jTxtSucChua4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelThongBao.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelThongBaoLayout = new javax.swing.GroupLayout(panelThongBao);
        panelThongBao.setLayout(panelThongBaoLayout);
        panelThongBaoLayout.setHorizontalGroup(
            panelThongBaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelThongBaoLayout.setVerticalGroup(
            panelThongBaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 49, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelThongBao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelMenuChuong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(21, 21, 21)
                        .addComponent(panelMenuLoaiChuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelMenuLoaiChuong, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelMenuChuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(panelThongBao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void showDanhSachChuong(String idMaChuong)
    {
        HeoBUS objHeoBUS=new HeoBUS();
          ResultSet rs=objHeoBUS.getChuong(idMaChuong);
          DefaultTableModel model;
            model = (DefaultTableModel) tableChuong.getModel();
            model.getDataVector().removeAllElements();
            model.fireTableDataChanged();
            
          try
          {
          while(rs.next())
          {
              ChuongELE tempCH = new ChuongELE(rs.getString("MaChuong"),rs.getString("MaLoaiChuong"),rs.getInt("SoLuongHeoDangChua"));
              lsC.add(tempCH);
                Vector vector=new Vector();
                vector.add(tempCH.getMaChuong());
          
                vector.add(tempCH.getSoLuongHeoDangChua());
                 model.addRow(vector);
          }
          }
          catch(SQLException exc)
          {
              System.out.println(exc);
          }
    }
    private void jLbXemDanhSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbXemDanhSachMouseClicked
        // TODO add your handling code here:
        showDanhSachChuong("LC01");

    }//GEN-LAST:event_jLbXemDanhSachMouseClicked

    private void JTxtTenChuong0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTxtTenChuong0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTxtTenChuong0ActionPerformed

    private void tableChuongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableChuongMouseClicked
        // TODO add your handling code here:
        int row = tableChuong.getSelectedRow();
            
            String valueTableChuong = tableChuong.getModel().getValueAt(row, 0).toString();
            
            HeoBUS hb=new HeoBUS();
            //chinh table
            DefaultTableModel model;
            model = (DefaultTableModel) TableHeo.getModel();
            model.getDataVector().removeAllElements();
            model.fireTableDataChanged();
            
            ResultSet rs=hb.getTableHeo(valueTableChuong);
            
            try {
                while(rs.next())
                {
                   
                   Vector vector=new Vector();
                vector.add(rs.getString("MaHeo"));
          
                vector.add(rs.getString("TinhTrang"));
                
                vector.add(rs.getString("GiaNhap"));
                vector.add(rs.getString("XuatXu"));
                vector.add(rs.getString("HeoMe"));
                vector.add(rs.getString("HeoCha"));
                model.addRow(vector);
                }
                
            } catch (SQLException ex) {
                Logger.getLogger(HeoGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_tableChuongMouseClicked

    private void panelMenuChuongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMenuChuongMouseClicked
        // TODO add your handling code here:
         showDanhSachChuong("LC01");
    }//GEN-LAST:event_panelMenuChuongMouseClicked

    private void lblAddPigMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddPigMouseClicked
        // TODO add your handling code here:
        String sTestMaChuong= (String) tableChuong.getModel().getValueAt(tableChuong.getSelectedRow(), 0);
        System.out.println(sTestMaChuong);
        JFrame AddPigFr=new ThemHeoConGUI();
        AddPigFr.setVisible(true);
        
        
    }//GEN-LAST:event_lblAddPigMouseClicked
       private void setLbColor(JLabel jlb) {
        jlb.setForeground(new Color(0,51,51)); //To change body of generated methods, choose Tools | Templates.
        jlb.setForeground(new Color(0,102,102));
    }

    private void resetLblColor(JLabel jlb) {
         jlb.setForeground(new Color(204,0,0)); //To change body of generated methods, choose Tools | Templates.
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTxtTenChuong0;
    private javax.swing.JTextField JTxtTenChuong1;
    private javax.swing.JTextField JTxtTenChuong2;
    private javax.swing.JTextField JTxtTenChuong3;
    private javax.swing.JTextField JTxtTenChuong4;
    private javax.swing.JTextField JtxtSoLuongChuong;
    private javax.swing.JTextField JtxtSoLuongChuong1;
    private javax.swing.JTextField JtxtSoLuongChuong2;
    private javax.swing.JTextField JtxtSoLuongChuong3;
    private javax.swing.JTextField JtxtSoLuongHeo4;
    private javax.swing.JTable TableHeo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLbChoAn;
    private javax.swing.JLabel jLbSoLuongHeo;
    private javax.swing.JLabel jLbSoLuongHeo1;
    private javax.swing.JLabel jLbSoLuongHeo2;
    private javax.swing.JLabel jLbSoLuongHeo3;
    private javax.swing.JLabel jLbSoLuongHeo4;
    private javax.swing.JLabel jLbSucChua;
    private javax.swing.JLabel jLbSucChua1;
    private javax.swing.JLabel jLbSucChua2;
    private javax.swing.JLabel jLbSucChua3;
    private javax.swing.JLabel jLbSucChua4;
    private javax.swing.JLabel jLbThemHeo;
    private javax.swing.JLabel jLbXemDanhSach;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTxtSucChua;
    private javax.swing.JTextField jTxtSucChua1;
    private javax.swing.JTextField jTxtSucChua2;
    private javax.swing.JTextField jTxtSucChua3;
    private javax.swing.JTextField jTxtSucChua4;
    private javax.swing.JTextField jTxt_TimKiem;
    private javax.swing.JLabel lblAddPig;
    private javax.swing.JLabel lblEat;
    private javax.swing.JPanel panelMenuChuong;
    private javax.swing.JPanel panelMenuLoaiChuong;
    private javax.swing.JPanel panelThongBao;
    private javax.swing.JTable tableChuong;
    // End of variables declaration//GEN-END:variables
}
