/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JPanel;
import Business.HeoBUS;
import java.sql.Array;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import Element.LoaiChuongELE;
import Element.ChuongELE;
import javax.swing.JFrame;
/**
 *
 * @author cuhoa_000
 */
public class HeoGUI extends javax.swing.JPanel {

    /**
     * Creates new form HeoGUI
     */
    
    ArrayList<LoaiChuongELE> lsLC=new ArrayList();
    ArrayList<ChuongELE> lsC=new ArrayList();
    public HeoGUI() {
        initComponents();
        showInfo();
        
    }
    private  void showInfo()
    {
        showMenuLoaiChuong();
        JtxtSoLuongChuong.setText(lsLC.get(0).getSoLuongChuong());
        JtxtSoLuongChuong1.setText(lsLC.get(1).getSoLuongChuong());
        JtxtSoLuongChuong2.setText(lsLC.get(2).getSoLuongChuong());
        JtxtSoLuongChuong3.setText(lsLC.get(3).getSoLuongChuong());
        
        jTxtSucChua.setText(lsLC.get(0).getQuiDinh());
        jTxtSucChua1.setText(lsLC.get(1).getQuiDinh());
        jTxtSucChua2.setText(lsLC.get(2).getQuiDinh());
        jTxtSucChua3.setText(lsLC.get(3).getQuiDinh());
        
    }
  
      private void showMenuLoaiChuong()
      {
          HeoBUS objHeo=new HeoBUS();
          ResultSet rs= objHeo.getLoaiChuong(); //loai Chuong
          
          int i=0;
          
          try
          {
              while(rs.next())
              {
                  int itemp=objHeo.getSoLuongChuong(rs.getString("MaLoaiChuong"));
                  LoaiChuongELE tempLC=new LoaiChuongELE(rs.getString("MaLoaiChuong"),rs.getString("TenLoaiChuong"),
                          rs.getInt("QuyDinhSoLuong"),itemp);              
                  lsLC.add(tempLC);
                  
                  
              }
          }
          catch(SQLException exc)
          {
              System.out.println(exc);
          }
       
      }
     
//      private void showMenuChuong()
//      {
//          HeoBUS objHeoBUS=new HeoBUS();
//          ResultSet rs=objHeoBUS.getChuong();
//          int i=0;
//          try
//          {
//          while(rs.next())
//          {
//              ChuongELE tempCH = new ChuongELE(rs.getString("MaChuong"),rs.getString("MaLoaiChuong"),rs.getInt("SoLuongHeoDangChua"));
//              lsC.add(tempCH);
//              ResultSet rsL=objHeoBUS.getLoaiChuong("LC01");
//              while(rsL.next())
//              {
//              
//              LoaiChuongELE tempLC=new LoaiChuongELE(rsL.getString("MaLoaiChuong"),rsL.getString("MaLoaiHeo"),rsL.getString("TenLoaiChuong"),rsL.getInt("QuyDinhSoLuong"));
//               
//              lsLC.add(tempLC);
//              }
//          }
//          }
//          catch(SQLException exc)
//          {
//              System.out.println(exc);
//          }
//         
//          
//         
//          String sSoLuong =Integer.toString(lsC.get(0).getSoLuongHeoDangChua());
//          JtxtSoLuongHeo.setText(sSoLuong);
//          String sSucChua= Integer.toString(lsLC.get(0).getQuiDinh());
//          jTxtSucChua.setText(sSucChua);
//          
//      }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenuLC = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLbSoLuongHeo1 = new javax.swing.JLabel();
        JtxtSoLuongChuong1 = new javax.swing.JTextField();
        jLbSucChua1 = new javax.swing.JLabel();
        jTxtSucChua1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        panelMenuChuong = new javax.swing.JPanel();
        jLbSoLuongHeo = new javax.swing.JLabel();
        JtxtSoLuongChuong = new javax.swing.JTextField();
        jLbSucChua = new javax.swing.JLabel();
        jTxtSucChua = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLbSoLuongHeo2 = new javax.swing.JLabel();
        jLbSucChua2 = new javax.swing.JLabel();
        jTxtSucChua2 = new javax.swing.JTextField();
        JtxtSoLuongChuong2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLbSucChua3 = new javax.swing.JLabel();
        jLbSoLuongHeo3 = new javax.swing.JLabel();
        jTxtSucChua3 = new javax.swing.JTextField();
        JtxtSoLuongChuong3 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLbSoLuongHeo4 = new javax.swing.JLabel();
        jLbSucChua4 = new javax.swing.JLabel();
        jTxtSucChua4 = new javax.swing.JTextField();
        JtxtSoLuongHeo4 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        panelThongBao = new javax.swing.JPanel();
        panelMenuLoaiChuong = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableHeo = new javax.swing.JTable();
        jTxt_TimKiem = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableChuong = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lblAddPig = new javax.swing.JLabel();
        lblEat = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();

        setBackground(new java.awt.Color(235, 233, 233));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelMenuLC.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLbSoLuongHeo1.setText("Số Lượng Chuồng:");
        jPanel1.add(jLbSoLuongHeo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 34, -1, -1));
        jPanel1.add(JtxtSoLuongChuong1, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 31, 27, -1));

        jLbSucChua1.setText("Sức chứa:");
        jPanel1.add(jLbSucChua1, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 60, 90, -1));
        jPanel1.add(jTxtSucChua1, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 57, 26, -1));

        jLabel5.setBackground(new java.awt.Color(0, 182, 121));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Wind Speed Less 1_100px.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel5.setIconTextGap(3);
        jLabel5.setOpaque(true);
        jLabel5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, -1, 87));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 114, 63));
        jLabel6.setText("CHUỒNG HEO NÁI MANG THAI");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 11, -1, -1));

        panelMenuLC.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 290, 90));

        panelMenuChuong.setBackground(new java.awt.Color(255, 255, 255));
        panelMenuChuong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelMenuChuongMouseClicked(evt);
            }
        });
        panelMenuChuong.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLbSoLuongHeo.setText("Số Lượng Chuồng:");
        panelMenuChuong.add(jLbSoLuongHeo, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 34, -1, -1));
        panelMenuChuong.add(JtxtSoLuongChuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 31, 29, -1));

        jLbSucChua.setText("Sức chứa:");
        panelMenuChuong.add(jLbSucChua, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 60, 89, -1));
        panelMenuChuong.add(jTxtSucChua, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 57, 29, -1));

        jLabel7.setBackground(new java.awt.Color(0, 182, 121));
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Wind Speed Less 1_100px.png"))); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel7.setIconTextGap(3);
        jLabel7.setOpaque(true);
        jLabel7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        panelMenuChuong.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, -1, 87));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 114, 63));
        jLabel8.setText("CHUỒNG HEO NÁI ĐẺ CON");
        panelMenuChuong.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 11, -1, -1));

        panelMenuLC.add(panelMenuChuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 290, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLbSoLuongHeo2.setText("Số Lượng Chuồng:");
        jPanel2.add(jLbSoLuongHeo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

        jLbSucChua2.setText("Sức chứa:");
        jPanel2.add(jLbSucChua2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 83, -1));
        jPanel2.add(jTxtSucChua2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 32, -1));
        jPanel2.add(JtxtSoLuongChuong2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 32, -1));

        jLabel9.setBackground(new java.awt.Color(0, 182, 121));
        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Wind Speed Less 1_100px.png"))); // NOI18N
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel9.setIconTextGap(3);
        jLabel9.setOpaque(true);
        jLabel9.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, -1, 87));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 114, 63));
        jLabel11.setText("CHUỒNG HEO ĐỰC GIỐNG");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 11, -1, -1));

        panelMenuLC.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 290, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLbSucChua3.setText("Sức chứa:");
        jPanel4.add(jLbSucChua3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 89, -1));

        jLbSoLuongHeo3.setText("Số Lượng Chuồng:");
        jPanel4.add(jLbSoLuongHeo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));
        jPanel4.add(jTxtSucChua3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 34, -1));

        JtxtSoLuongChuong3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtxtSoLuongChuong3ActionPerformed(evt);
            }
        });
        jPanel4.add(JtxtSoLuongChuong3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 34, -1));

        jLabel10.setBackground(new java.awt.Color(0, 182, 121));
        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Wind Speed Less 1_100px.png"))); // NOI18N
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel10.setIconTextGap(3);
        jLabel10.setOpaque(true);
        jLabel10.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, -1, 87));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 114, 63));
        jLabel12.setText("CHUỒNG HEO CHỜ PHỐI GIỐNG");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 11, -1, -1));

        panelMenuLC.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 290, -1));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLbSoLuongHeo4.setText("Số Lượng Chuồng:");
        jPanel6.add(jLbSoLuongHeo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

        jLbSucChua4.setText("Sức chứa:");
        jPanel6.add(jLbSucChua4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 89, -1));
        jPanel6.add(jTxtSucChua4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 34, -1));
        jPanel6.add(JtxtSoLuongHeo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 34, -1));

        jLabel3.setBackground(new java.awt.Color(0, 182, 121));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Wind Speed Less 1_100px.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel3.setIconTextGap(3);
        jLabel3.setOpaque(true);
        jLabel3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, -1, 87));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 114, 63));
        jLabel4.setText("CHUỒNG HEO THỊT");
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 11, -1, -1));

        panelMenuLC.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 290, 86));

        add(panelMenuLC, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 0, 320, 670));

        panelThongBao.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelThongBaoLayout = new javax.swing.GroupLayout(panelThongBao);
        panelThongBao.setLayout(panelThongBaoLayout);
        panelThongBaoLayout.setHorizontalGroup(
            panelThongBaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        panelThongBaoLayout.setVerticalGroup(
            panelThongBaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        add(panelThongBao, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 610, 600, 60));

        panelMenuLoaiChuong.setBackground(new java.awt.Color(255, 255, 255));

        TableHeo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TableHeo);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Item/loupe.png"))); // NOI18N

        tableChuong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã Chuồng", "Số Lượng Heo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableChuong.setToolTipText("");
        tableChuong.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tableChuong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableChuongMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tableChuong);

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DANH SÁCH CHUỒNG");
        jLabel1.setOpaque(true);

        lblAddPig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Item/plus (1).png"))); // NOI18N
        lblAddPig.setText("Thêm heo");
        lblAddPig.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAddPigMouseClicked(evt);
            }
        });

        lblEat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Item/restaurant.png"))); // NOI18N
        lblEat.setText("Cho Ăn");
        lblEat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEatMouseClicked(evt);
            }
        });

        jToggleButton1.setText("Chuyển chuồng");

        jToggleButton2.setText("Xuất chuồng");

        javax.swing.GroupLayout panelMenuLoaiChuongLayout = new javax.swing.GroupLayout(panelMenuLoaiChuong);
        panelMenuLoaiChuong.setLayout(panelMenuLoaiChuongLayout);
        panelMenuLoaiChuongLayout.setHorizontalGroup(
            panelMenuLoaiChuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLoaiChuongLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMenuLoaiChuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMenuLoaiChuongLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(84, 84, 84)
                        .addComponent(jTxt_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))
                    .addGroup(panelMenuLoaiChuongLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(13, 13, 13)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(panelMenuLoaiChuongLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblAddPig)
                .addGap(18, 18, 18)
                .addComponent(lblEat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addComponent(jToggleButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToggleButton2)
                .addGap(86, 86, 86))
        );
        panelMenuLoaiChuongLayout.setVerticalGroup(
            panelMenuLoaiChuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLoaiChuongLayout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addGroup(panelMenuLoaiChuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelMenuLoaiChuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTxt_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelMenuLoaiChuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelMenuLoaiChuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddPig, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEat)
                    .addGroup(panelMenuLoaiChuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jToggleButton1)
                        .addComponent(jToggleButton2)))
                .addGap(26, 26, 26))
        );

        add(panelMenuLoaiChuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 600, 600));
    }// </editor-fold>//GEN-END:initComponents

    private void showDanhSachChuong(String idMaChuong)
    {
        HeoBUS objHeoBUS=new HeoBUS();
          ResultSet rs=objHeoBUS.getChuong(idMaChuong);
          DefaultTableModel model;
            model = (DefaultTableModel) tableChuong.getModel();
            model.getDataVector().removeAllElements();
            model.fireTableDataChanged();
            
          try
          {
          while(rs.next())
          {
              ChuongELE tempCH = new ChuongELE(rs.getString("MaChuong"),rs.getString("MaLoaiChuong"),rs.getInt("SoLuongHeoDangChua"));
              lsC.add(tempCH);
                Vector vector=new Vector();
                vector.add(tempCH.getMaChuong());
          
                vector.add(tempCH.getSoLuongHeoDangChua());
                 model.addRow(vector);
          }
          }
          catch(SQLException exc)
          {
              System.out.println(exc);
          }
    }
    private void tableChuongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableChuongMouseClicked
        // TODO add your handling code here:
        int row = tableChuong.getSelectedRow();
            
            String valueTableChuong = tableChuong.getModel().getValueAt(row, 0).toString();
            
            HeoBUS hb=new HeoBUS();
            //chinh table
            DefaultTableModel model;
            model = (DefaultTableModel) TableHeo.getModel();
            model.getDataVector().removeAllElements();
            model.fireTableDataChanged();
            
            ResultSet rs=hb.getTableHeo(valueTableChuong);
            
            try {
                while(rs.next())
                {
                   
                   Vector vector=new Vector();
                vector.add(rs.getString("MaHeo"));
          
                vector.add(rs.getString("TinhTrang"));
                
                vector.add(rs.getString("GiaNhap"));
                vector.add(rs.getString("XuatXu"));
                vector.add(rs.getString("HeoMe"));
                vector.add(rs.getString("HeoCha"));
                model.addRow(vector);
                }
                
            } catch (SQLException ex) {
                Logger.getLogger(HeoGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_tableChuongMouseClicked

    private void panelMenuChuongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMenuChuongMouseClicked
        // TODO add your handling code here:
         showDanhSachChuong("LC01");
    }//GEN-LAST:event_panelMenuChuongMouseClicked


    private void lblAddPigMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddPigMouseClicked
        // TODO add your handling code here:
       String sMaChuong=(String) tableChuong.getModel().getValueAt(tableChuong.getSelectedRow(), 0);
        ThemHeoConGUI.getObj(sMaChuong).setVisible(true);
//        JFrame AddPigFr=new ThemHeoConGUI();
//        AddPigFr.setVisible(true);
        
        
    }//GEN-LAST:event_lblAddPigMouseClicked

    private void lblEatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEatMouseClicked
        // TODO add your handling code here:
        String sMaChuong=(String) tableChuong.getModel().getValueAt(tableChuong.getSelectedRow(), 0);
        ChoAnGUI.getObj(sMaChuong,"LC01","").setVisible(true);
    }//GEN-LAST:event_lblEatMouseClicked

    private void JtxtSoLuongChuong3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtxtSoLuongChuong3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtxtSoLuongChuong3ActionPerformed
       private void setLbColor(JLabel jlb) {
        jlb.setForeground(new Color(0,51,51)); //To change body of generated methods, choose Tools | Templates.
        jlb.setForeground(new Color(0,102,102));
    }

    private void resetLblColor(JLabel jlb) {
         jlb.setForeground(new Color(204,0,0)); //To change body of generated methods, choose Tools | Templates.
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JtxtSoLuongChuong;
    private javax.swing.JTextField JtxtSoLuongChuong1;
    private javax.swing.JTextField JtxtSoLuongChuong2;
    private javax.swing.JTextField JtxtSoLuongChuong3;
    private javax.swing.JTextField JtxtSoLuongHeo4;
    private javax.swing.JTable TableHeo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLbSoLuongHeo;
    private javax.swing.JLabel jLbSoLuongHeo1;
    private javax.swing.JLabel jLbSoLuongHeo2;
    private javax.swing.JLabel jLbSoLuongHeo3;
    private javax.swing.JLabel jLbSoLuongHeo4;
    private javax.swing.JLabel jLbSucChua;
    private javax.swing.JLabel jLbSucChua1;
    private javax.swing.JLabel jLbSucChua2;
    private javax.swing.JLabel jLbSucChua3;
    private javax.swing.JLabel jLbSucChua4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JTextField jTxtSucChua;
    private javax.swing.JTextField jTxtSucChua1;
    private javax.swing.JTextField jTxtSucChua2;
    private javax.swing.JTextField jTxtSucChua3;
    private javax.swing.JTextField jTxtSucChua4;
    private javax.swing.JTextField jTxt_TimKiem;
    private javax.swing.JLabel lblAddPig;
    private javax.swing.JLabel lblEat;
    private javax.swing.JPanel panelMenuChuong;
    private javax.swing.JPanel panelMenuLC;
    private javax.swing.JPanel panelMenuLoaiChuong;
    private javax.swing.JPanel panelThongBao;
    private javax.swing.JTable tableChuong;
    // End of variables declaration//GEN-END:variables
}
