/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import Business.ThucAnBUS;
import Business.ThucAnLoaiBUS;
import java.sql.Date;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


public class SuaThucAnLoaiGUI extends javax.swing.JFrame {

    private static ThucAnLoaiBUS tal;
    
    public SuaThucAnLoaiGUI(ThucAnLoaiBUS tal) {
        initComponents();
        this.tal=tal;
        HienThiThongTin();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTenThucAn = new javax.swing.JTextField();
        txtSoLuong = new javax.swing.JTextField();
        dcNgayLoai = new com.toedter.calendar.JDateChooser();
        btnLuuSua = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("SỬA THỨC ĂN LOẠI");

        jLabel2.setText("Thức ăn:");

        jLabel3.setText("Ngày loại:");

        jLabel4.setText("Số lượng:");

        btnLuuSua.setText("Lưu sửa");
        btnLuuSua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLuuSuaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jLabel1)
                        .addGap(0, 143, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addGap(30, 30, 30)
                        .addComponent(dcNgayLoai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnLuuSua)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtTenThucAn)
                            .addComponent(txtSoLuong))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTenThucAn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(dcNgayLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnLuuSua)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Cắt chuỗi khi gặp "-"
    
    public int LayNam (String s)
    {
        int n= s.length();
        String[] lh;
        lh = s.split("-"); 
        int nam= Integer.parseInt(lh[0]);
        return nam;
    }  
    //lấy tháng
    public int LayThang (String s)
    {
        int n= s.length();
        String[] lh;
        lh = s.split("-"); 
        int thang= Integer.parseInt(lh[1]);
        return thang;
    }  
    //Lấy ngày
    public int LayNgay (String s)
    {
        int n= s.length();
        String[] lh;
        lh = s.split("-"); 
        int ngay= Integer.parseInt(lh[2]);
        return ngay;
    }  
//Hiển thị thông tin
    private void HienThiThongTin()
    {
        ThucAnBUS ta= new ThucAnBUS();
        ta.getThucAnBangMa(tal.getMaThucAn());
        
        txtTenThucAn.setText(ta.getTenThucAn());
        txtSoLuong.setText(String.valueOf(tal.getSoLuong()));
        String ngayloai=tal.getNgayLoai();
        
        SimpleDateFormat df=new SimpleDateFormat("yyyy-MM-dd");
        int dd=LayNgay(ngayloai);
        
        int MM;
        int yyyy;
        
        
        
//        try {
//            //date1 =  (Date) df.parse(ngayloai);
              //dcNgayLoai.setDate(date1);
//        } catch (ParseException ex) {
//            Logger.getLogger(SuaThucAnLoaiGUI.class.getName()).log(Level.SEVERE, null, ex);
//        }
        
    }
//Kiểm tra các trường bắt buộc
    private boolean KiemTraCacTruongBatBuoc()
    {
        if(dcNgayLoai.getDate()==null || txtSoLuong.getText()==null)
        {
            return false;
        }
        return true;
    }
    private void btnLuuSuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLuuSuaMouseClicked
        if(KiemTraCacTruongBatBuoc()==false)
        {
            JOptionPane.showMessageDialog(null, "Bạn nhập thiếu thông tin");
            
        }
        else{
        DateFormat df= new SimpleDateFormat("yyyy-MM-dd");
        String ngayloai=df.format(dcNgayLoai.getDate());
        double soluong= Double.parseDouble(txtSoLuong.getText());
        ThucAnLoaiBUS tal1= new ThucAnLoaiBUS(0,tal.getMaThucAn(),soluong , ngayloai );
        ThucAnBUS ta= new ThucAnBUS(tal.getMaThucAn(), "", "", 0, "");
        try {
            if(tal1.ThemThucAnLoai(tal1)==true)
            {
                JOptionPane.showMessageDialog(null, "Thành công");
                ta.CapNhatTonKho(-soluong);
                
            }
            else JOptionPane.showMessageDialog(null, "Thất bại");
        } catch (SQLException ex) {
            Logger.getLogger(ThemThucAnLoaiGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_btnLuuSuaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuaThucAnLoaiGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuaThucAnLoaiGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuaThucAnLoaiGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuaThucAnLoaiGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SuaThucAnLoaiGUI(tal).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLuuSua;
    private com.toedter.calendar.JDateChooser dcNgayLoai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenThucAn;
    // End of variables declaration//GEN-END:variables
}
