/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;
import  Business.TaiKhoanBUS;
import static java.awt.SystemColor.text;
import java.sql.ResultSet;
import java.sql.SQLException;
/**
 *
 * @author cuhoa_000
 */
public class TaiKhoanGUI extends javax.swing.JPanel {

    /**
     * Creates new form TaiKhoanGUI
     */
    public TaiKhoanGUI() {
        initComponents();
        showText();
    }

    private void showText()
    {
        TaiKhoanBUS bs=new TaiKhoanBUS();
        ResultSet rs=bs.getTaiKhoan();
        try
        {
            while(rs.next())
            {
                txtTest.setText(rs.getString("HoTen"));
            }
            
        }
        catch(SQLException exc)
        {
            System.out.println(exc);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTest = new javax.swing.JTextField();

        txtTest.setText("jTextField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(txtTest, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(463, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(txtTest, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(303, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField txtTest;
    // End of variables declaration//GEN-END:variables
}
