/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import Business.HeoBUS;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import gui.HeoGUI;

/**
 *
 * @author cuhoa_000
 */
public class ThemHeoConGUI extends javax.swing.JFrame {

    /**
     * Creates new form ThemHeoGUI
     */
    
    private static ThemHeoConGUI obj=null;
    public static ThemHeoConGUI getObj(String sMaChuong)
    { if(obj==null){
        obj=new ThemHeoConGUI(sMaChuong); 
        }
        return obj; 
    }

    static Object getObj() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    public ThemHeoConGUI(String sMaChuong) {
        initComponents();
        txtMaChuong.setText(sMaChuong);
    }
     public ThemHeoConGUI() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelContain = new javax.swing.JPanel();
        DateNS = new com.toedter.calendar.JDateChooser();
        txtMaHeoCha = new javax.swing.JTextField();
        txtMaHeoMe = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableThemHeoCon = new javax.swing.JTable();
        spnCanNang = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        cbGioiTinh = new javax.swing.JComboBox<>();
        lbMaChuong = new javax.swing.JLabel();
        lbGioiTinh = new javax.swing.JLabel();
        txtMaChuong = new javax.swing.JTextField();
        lbXacNhan = new javax.swing.JLabel();
        lbXoa = new javax.swing.JLabel();
        lbThem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("THÊM HEO CON");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelContain.setBackground(new java.awt.Color(255, 255, 255));
        panelContain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DateNS.setDateFormatString("yyyy-MM-dd\n");
        panelContain.add(DateNS, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 72, 150, -1));
        panelContain.add(txtMaHeoCha, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 20, 80, -1));
        panelContain.add(txtMaHeoMe, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 20, 79, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 102));
        jLabel3.setText("Mã Heo Mẹ");
        panelContain.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 23, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 102));
        jLabel4.setText("Mã Heo Cha");
        panelContain.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 23, -1, -1));

        tableThemHeoCon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Cân nặng", "Giới tính", "Chuồng"
            }
        ));
        jScrollPane1.setViewportView(tableThemHeoCon);

        panelContain.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 152, 376, 246));
        panelContain.add(spnCanNang, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 46, 79, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 102));
        jLabel2.setText("Cân nặng (kg)");
        panelContain.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 49, -1, -1));

        cbGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đực", "Cái" }));
        panelContain.add(cbGioiTinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 46, 80, -1));

        lbMaChuong.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbMaChuong.setForeground(new java.awt.Color(0, 153, 102));
        lbMaChuong.setText("Mã chuồng:");
        panelContain.add(lbMaChuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 77, -1, -1));

        lbGioiTinh.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbGioiTinh.setForeground(new java.awt.Color(0, 153, 102));
        lbGioiTinh.setText("Giới tính");
        panelContain.add(lbGioiTinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 49, -1, -1));

        txtMaChuong.setText("jTextField2");
        panelContain.add(txtMaChuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 72, 79, 25));

        lbXacNhan.setBackground(new java.awt.Color(0, 153, 102));
        lbXacNhan.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbXacNhan.setForeground(new java.awt.Color(255, 255, 255));
        lbXacNhan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbXacNhan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Item/Checkmark_25px.png"))); // NOI18N
        lbXacNhan.setText("XÁC NHẬN");
        lbXacNhan.setToolTipText("");
        lbXacNhan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbXacNhan.setOpaque(true);
        lbXacNhan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbXacNhanMouseClicked(evt);
            }
        });
        panelContain.add(lbXacNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 416, 144, -1));

        lbXoa.setBackground(new java.awt.Color(0, 153, 102));
        lbXoa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbXoa.setForeground(new java.awt.Color(255, 255, 255));
        lbXoa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Item/Eraser_25px.png"))); // NOI18N
        lbXoa.setText("XÓA");
        lbXoa.setToolTipText("");
        lbXoa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbXoa.setOpaque(true);
        lbXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbXoaMouseClicked(evt);
            }
        });
        panelContain.add(lbXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 115, 79, 26));

        lbThem.setBackground(new java.awt.Color(0, 153, 102));
        lbThem.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbThem.setForeground(new java.awt.Color(255, 255, 255));
        lbThem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Item/Positive_25px.png"))); // NOI18N
        lbThem.setText("THÊM");
        lbThem.setToolTipText("");
        lbThem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbThem.setOpaque(true);
        lbThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbThemMouseClicked(evt);
            }
        });
        panelContain.add(lbThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 115, 79, 26));

        getContentPane().add(panelContain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 457));

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    private void lbThemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbThemMouseClicked
       DefaultTableModel model;
            model = (DefaultTableModel) tableThemHeoCon.getModel();
            Vector vector=new Vector();
            int stt=tableThemHeoCon.getRowCount()+1;
            vector.add(stt);
            vector.add(spnCanNang.getValue());
            vector.add(cbGioiTinh.getSelectedItem());
            vector.add(txtMaChuong.getText().toString());
            model.addRow(vector);
    }//GEN-LAST:event_lbThemMouseClicked

    private void lbXoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbXoaMouseClicked
        try
        {
       ((DefaultTableModel)tableThemHeoCon.getModel()).removeRow(tableThemHeoCon.getSelectedRow());
        }
        catch(Exception exc)
        {
            System.out.println(exc);
        }
    }//GEN-LAST:event_lbXoaMouseClicked

    private void lbXacNhanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbXacNhanMouseClicked
         HeoBUS objHeo=new HeoBUS();
        int n=tableThemHeoCon.getRowCount();
        
       ArrayList<String> lstCanNang=new ArrayList();
        ArrayList<String> lstGioiTinh=new ArrayList();
        
        
        String sDateNS=((JTextField)DateNS.getDateEditor().getUiComponent()).getText();
        //System.out.println(sDateNS);
        int iCountTrue=0;
        for(int i=0;i<n;i++)
        {
        try {
            String sCanNang=tableThemHeoCon.getModel().getValueAt(i, 1).toString();
            String sGioiTinh=tableThemHeoCon.getModel().getValueAt(i,2).toString();
            String sIdChuong=tableThemHeoCon.getModel().getValueAt(i, 3).toString();
            if(sGioiTinh =="Đực") 
            sGioiTinh="D";
            else
            sGioiTinh="C";
            
            if(objHeo.ThemHeoCon(txtMaHeoMe.getText(),txtMaHeoCha.getText(),sDateNS,sGioiTinh))
            {
                
                HeoBUS objMAHEO=new HeoBUS();
                String sIdHeo=objMAHEO.getIDHeo();
                if(objHeo.ThemCanNang(sCanNang, sDateNS, sIdHeo))
                    if(objHeo.ThemCtChuong(sIdHeo, sIdChuong, sDateNS))
                    iCountTrue++;
               
            }
            objHeo.UpdateChuong();
            }
        catch (SQLException ex) 
            {
            Logger.getLogger(ThemHeoConGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if(iCountTrue==n)
                JOptionPane.showMessageDialog(null, "Thêm heo thành công",
                  "THÔNG BÁO", JOptionPane.INFORMATION_MESSAGE);
        else
             JOptionPane.showMessageDialog(null, "Có lỗi trong quá trình nhập heo",
                  "THÔNG BÁO", JOptionPane.WARNING_MESSAGE);
            
    }//GEN-LAST:event_lbXacNhanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemHeoConGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemHeoConGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemHeoConGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemHeoConGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThemHeoConGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DateNS;
    private javax.swing.JComboBox<String> cbGioiTinh;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbGioiTinh;
    private javax.swing.JLabel lbMaChuong;
    private javax.swing.JLabel lbThem;
    private javax.swing.JLabel lbXacNhan;
    private javax.swing.JLabel lbXoa;
    private javax.swing.JPanel panelContain;
    private javax.swing.JSpinner spnCanNang;
    private javax.swing.JTable tableThemHeoCon;
    private javax.swing.JTextField txtMaChuong;
    private javax.swing.JTextField txtMaHeoCha;
    private javax.swing.JTextField txtMaHeoMe;
    // End of variables declaration//GEN-END:variables
}
