/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import Business.ThuocBUS;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cuhoa_000
 */
public class ThuocGUI extends javax.swing.JFrame {
    
    ArrayList <String> lstMaThuoc =new ArrayList(); //Mang luu ma thuoc

    /**
     * Tao doi tuong obj thuoc ThuocGUI (obj chi co duy nhat)
     * Neu obj da mo thi se khong mo form lan nua
     */
    private static ThuocGUI obj=null;
    public static ThuocGUI getObj (String sMaHeo)
    {
        if(obj==null)
        {
            obj=new ThuocGUI(sMaHeo);
        }
        return obj;
    }
    public ThuocGUI(String sMaHeo)
    {
        initComponents();
        lbMaHeo.setText(sMaHeo);
        ShowInfo();
    }   
    public ThuocGUI() {
        initComponents();
    }
    private void ShowInfo() //Hien thi cac thong tin khi load form
    {
        //lam sach vung chua
        lstMaThuoc.clear();
        cbTenThuoc.removeAllItems();
        ThuocBUS objThuoc=new ThuocBUS();
        ResultSet rs=objThuoc.getThuoc();
        try
        {
            while(rs.next())
            {
                cbTenThuoc.addItem(rs.getString("TenThuoc"));
                lstMaThuoc.add(rs.getString("MaThuoc"));
            }
        }
        catch(SQLException exc)
        {
            System.out.println("Loi o ShowInfo ThuocGUI" +exc);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelContain = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableThuoc = new javax.swing.JTable();
        lbMaHeo = new javax.swing.JLabel();
        dateNgayDungThuoc = new com.toedter.calendar.JDateChooser();
        cbTenThuoc = new javax.swing.JComboBox<>();
        spLieuLuong = new javax.swing.JSpinner();
        cbDonVi = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbXacNhan = new javax.swing.JLabel();
        lbThem = new javax.swing.JLabel();
        lbXoa = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelContain.setBackground(new java.awt.Color(255, 255, 255));
        panelContain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableThuoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Stt", "Mã Thuốc", "Tên Thuốc", "Liều Lượng", "Đơn vị tính"
            }
        ));
        jScrollPane1.setViewportView(tableThuoc);

        panelContain.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 156, 371, 166));

        lbMaHeo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbMaHeo.setText("jLabel2");
        panelContain.add(lbMaHeo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        dateNgayDungThuoc.setDateFormatString("yyyy-MM-dd\n");
        panelContain.add(dateNgayDungThuoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 71, 124, -1));

        cbTenThuoc.setEditable(true);
        cbTenThuoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbTenThuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTenThuocActionPerformed(evt);
            }
        });
        panelContain.add(cbTenThuoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 71, 110, -1));
        panelContain.add(spLieuLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 40, 73, -1));

        cbDonVi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CC", "ML", "Gram", " " }));
        panelContain.add(cbDonVi, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 40, 55, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 102));
        jLabel3.setText("Mã Heo:");
        panelContain.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 102));
        jLabel4.setText("Tên thuốc:");
        panelContain.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 102));
        jLabel5.setText("Ngày:");
        panelContain.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 102));
        jLabel6.setText("Liều dùng:");
        panelContain.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, -1, -1));

        lbXacNhan.setBackground(new java.awt.Color(0, 153, 102));
        lbXacNhan.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbXacNhan.setForeground(new java.awt.Color(255, 255, 255));
        lbXacNhan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbXacNhan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Item/Checkmark_25px.png"))); // NOI18N
        lbXacNhan.setText("XÁC NHẬN");
        lbXacNhan.setToolTipText("");
        lbXacNhan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbXacNhan.setOpaque(true);
        lbXacNhan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbXacNhanMouseClicked(evt);
            }
        });
        panelContain.add(lbXacNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 144, -1));

        lbThem.setBackground(new java.awt.Color(0, 153, 102));
        lbThem.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbThem.setForeground(new java.awt.Color(255, 255, 255));
        lbThem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Item/Positive_25px.png"))); // NOI18N
        lbThem.setText("THÊM");
        lbThem.setToolTipText("");
        lbThem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbThem.setOpaque(true);
        lbThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbThemMouseClicked(evt);
            }
        });
        panelContain.add(lbThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 115, 79, 26));

        lbXoa.setBackground(new java.awt.Color(0, 153, 102));
        lbXoa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbXoa.setForeground(new java.awt.Color(255, 255, 255));
        lbXoa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Item/Eraser_25px.png"))); // NOI18N
        lbXoa.setText("XÓA");
        lbXoa.setToolTipText("");
        lbXoa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbXoa.setOpaque(true);
        lbXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbXoaMouseClicked(evt);
            }
        });
        panelContain.add(lbXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 115, 79, 26));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContain, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContain, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbTenThuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTenThuocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTenThuocActionPerformed

    private void lbXacNhanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbXacNhanMouseClicked
        ThuocBUS objThuoc=new ThuocBUS();
        int n=tableThuoc.getRowCount(); //So luong hang trong bang
        String sDate=((JTextField) dateNgayDungThuoc.getDateEditor().getUiComponent()).getText();
        int iCheck=0; //Kiem tra dung sai khi nhap
        for(int i=0;i<n;i++)
        {
            try
            {
                String sMaThuoc =tableThuoc.getModel().getValueAt(i,1).toString();
                String SLieuLuong=tableThuoc.getModel().getValueAt(i,3).toString();
                String sDonVi= tableThuoc.getModel().getValueAt(i,4).toString();
                if(objThuoc.ThemThongTinDungThuoc(lbMaHeo.getText(), SLieuLuong, sMaThuoc, sDate, sDonVi));
                {
                    iCheck++;
                }
            } catch (SQLException ex) {
                Logger.getLogger(ThuocGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if(iCheck ==n)
             JOptionPane.showMessageDialog(null, "Thêm Thuốc thành công",
                  "THÔNG BÁO", JOptionPane.INFORMATION_MESSAGE);
        else
             JOptionPane.showMessageDialog(null, "Có lỗi trong quá trình nhập",
                  "THÔNG BÁO", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_lbXacNhanMouseClicked

    private void lbThemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbThemMouseClicked
     DefaultTableModel model =(DefaultTableModel) tableThuoc.getModel();
        Vector vector= new Vector();
        int stt= tableThuoc.getRowCount()+1; //Cot So thu tu
        //themm cac gia tri vao vector
        vector.add(stt);
        vector.add(lstMaThuoc.get(cbTenThuoc.getSelectedIndex()));
        vector.add(cbTenThuoc.getSelectedItem());
        vector.add(spLieuLuong.getValue());
        vector.add(cbDonVi.getSelectedItem());
        int iLieuLuong =(int) spLieuLuong.getValue();
        if(iLieuLuong > 0)
            model.addRow(vector); //them vao bang khi lieu luong >0
    }//GEN-LAST:event_lbThemMouseClicked

    private void lbXoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbXoaMouseClicked
        try
        {
        ((DefaultTableModel)tableThuoc.getModel()).removeRow(tableThuoc.getSelectedRow());
        }
        catch(Exception exc)
        {
            System.out.println("Loi o btn Xoa ThuocGUI "+exc);
        }
    }//GEN-LAST:event_lbXoaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThuocGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThuocGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThuocGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThuocGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThuocGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbDonVi;
    private javax.swing.JComboBox<String> cbTenThuoc;
    private com.toedter.calendar.JDateChooser dateNgayDungThuoc;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbMaHeo;
    private javax.swing.JLabel lbThem;
    private javax.swing.JLabel lbXacNhan;
    private javax.swing.JLabel lbXoa;
    private javax.swing.JPanel panelContain;
    private javax.swing.JSpinner spLieuLuong;
    private javax.swing.JTable tableThuoc;
    // End of variables declaration//GEN-END:variables
}
