/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import Business.ThuocBUS;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cuhoa_000
 */
public class ThuocGUI extends javax.swing.JFrame {
    
    ArrayList <String> lstMaThuoc =new ArrayList(); //Mang luu ma thuoc

    /**
     * Tao doi tuong obj thuoc ThuocGUI (obj chi co duy nhat)
     * Neu obj da mo thi se khong mo form lan nua
     */
    private static ThuocGUI obj=null;
    public static ThuocGUI getObj (String sMaHeo)
    {
        if(obj==null)
        {
            obj=new ThuocGUI(sMaHeo);
        }
        return obj;
    }
    public ThuocGUI(String sMaHeo)
    {
        initComponents();
        lbMaHeo.setText(sMaHeo);
        ShowInfo();
    }   
    public ThuocGUI() {
        initComponents();
    }
    private void ShowInfo() //Hien thi cac thong tin khi load form
    {
        //lam sach vung chua
        lstMaThuoc.clear();
        cbTenThuoc.removeAllItems();
        ThuocBUS objThuoc=new ThuocBUS();
        ResultSet rs=objThuoc.getThuoc();
        try
        {
            while(rs.next())
            {
                cbTenThuoc.addItem(rs.getString("TenThuoc"));
                lstMaThuoc.add(rs.getString("MaThuoc"));
            }
        }
        catch(SQLException exc)
        {
            System.out.println("Loi o ShowInfo ThuocGUI" +exc);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableThuoc = new javax.swing.JTable();
        lblMaHeo = new javax.swing.JLabel();
        lbMaHeo = new javax.swing.JLabel();
        dateNgayDungThuoc = new com.toedter.calendar.JDateChooser();
        lbNgayDungThuoc = new javax.swing.JLabel();
        lbTenThuoc = new javax.swing.JLabel();
        cbTenThuoc = new javax.swing.JComboBox<>();
        lbLieuLuong = new javax.swing.JLabel();
        spLieuLuong = new javax.swing.JSpinner();
        cbDonVi = new javax.swing.JComboBox<>();
        btnThem = new javax.swing.JToggleButton();
        btnXoa = new javax.swing.JToggleButton();
        btnXacNhan = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tableThuoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Stt", "Mã Thuốc", "Tên Thuốc", "Liều Lượng", "Đơn vị tính"
            }
        ));
        jScrollPane1.setViewportView(tableThuoc);

        lblMaHeo.setText("Mã heo:");

        lbMaHeo.setText("jLabel2");

        dateNgayDungThuoc.setDateFormatString("yyyy-MM-dd\n");

        lbNgayDungThuoc.setText("Ngày dùng thuốc");

        lbTenThuoc.setText("Tên thuốc:");

        cbTenThuoc.setEditable(true);
        cbTenThuoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lbLieuLuong.setText("Liều lượng:");

        cbDonVi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CC", "ML", "Gram", " " }));

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnXacNhan.setText("Xác nhận");
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblMaHeo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbMaHeo)
                                .addGap(78, 78, 78)
                                .addComponent(lbNgayDungThuoc))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbTenThuoc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbTenThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(lbLieuLuong)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dateNgayDungThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(spLieuLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbDonVi, 0, 1, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(btnThem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnXoa))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(btnXacNhan)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbNgayDungThuoc)
                    .addComponent(dateNgayDungThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbMaHeo)
                        .addComponent(lblMaHeo)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTenThuoc)
                    .addComponent(cbTenThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbLieuLuong)
                    .addComponent(spLieuLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbDonVi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnXoa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnXacNhan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model =(DefaultTableModel) tableThuoc.getModel();
        Vector vector= new Vector();
        int stt= tableThuoc.getRowCount()+1; //Cot So thu tu
        //themm cac gia tri vao vector
        vector.add(stt);
        vector.add(lstMaThuoc.get(cbTenThuoc.getSelectedIndex()));
        vector.add(cbTenThuoc.getSelectedItem());
        vector.add(spLieuLuong.getValue());
        vector.add(cbDonVi.getSelectedItem());
        int iLieuLuong =(int) spLieuLuong.getValue();
        if(iLieuLuong > 0)
            model.addRow(vector); //them vao bang khi lieu luong >0
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        try
        {
        ((DefaultTableModel)tableThuoc.getModel()).removeRow(tableThuoc.getSelectedRow());
        }
        catch(Exception exc)
        {
            System.out.println("Loi o btn Xoa ThuocGUI "+exc);
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
        ThuocBUS objThuoc=new ThuocBUS();
        int n=tableThuoc.getRowCount(); //So luong hang trong bang
        String sDate=((JTextField) dateNgayDungThuoc.getDateEditor().getUiComponent()).getText();
        int iCheck=0; //Kiem tra dung sai khi nhap
        for(int i=0;i<n;i++)
        {
            try
            {
                String sMaThuoc =tableThuoc.getModel().getValueAt(i,1).toString();
                String SLieuLuong=tableThuoc.getModel().getValueAt(i,3).toString();
                String sDonVi= tableThuoc.getModel().getValueAt(i,4).toString();
                if(objThuoc.ThemThongTinDungThuoc(lbMaHeo.getText(), SLieuLuong, sMaThuoc, sDate, sDonVi));
                {
                    iCheck++;
                }
            } catch (SQLException ex) {
                Logger.getLogger(ThuocGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if(iCheck ==n)
             JOptionPane.showMessageDialog(null, "Thêm Thuốc thành công",
                  "THÔNG BÁO", JOptionPane.INFORMATION_MESSAGE);
        else
             JOptionPane.showMessageDialog(null, "Có lỗi trong quá trình nhập",
                  "THÔNG BÁO", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_btnXacNhanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThuocGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThuocGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThuocGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThuocGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThuocGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnThem;
    private javax.swing.JToggleButton btnXacNhan;
    private javax.swing.JToggleButton btnXoa;
    private javax.swing.JComboBox<String> cbDonVi;
    private javax.swing.JComboBox<String> cbTenThuoc;
    private com.toedter.calendar.JDateChooser dateNgayDungThuoc;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbLieuLuong;
    private javax.swing.JLabel lbMaHeo;
    private javax.swing.JLabel lbNgayDungThuoc;
    private javax.swing.JLabel lbTenThuoc;
    private javax.swing.JLabel lblMaHeo;
    private javax.swing.JSpinner spLieuLuong;
    private javax.swing.JTable tableThuoc;
    // End of variables declaration//GEN-END:variables
}
