/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import Business.CTHoaDonBUS;
import Business.HoaDonBUS;
import Business.KhachHangBUS;
import Element.HeoELE;
import Element.KhachHangELE;

import java.awt.HeadlessException;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Random;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JTextField;
/**
 *
 * @author namminhlp
 */
public class XuatChuongGUI extends javax.swing.JFrame {

    private int DonGia;
    private static XuatChuongGUI obj=null;
    DefaultTableModel model;
     
    /**
     * Creates new form XuatChuongGUI
     */
    public XuatChuongGUI() {
        initComponents();
        
    }
    public static XuatChuongGUI getObj(ArrayList<HeoELE> lsHeoXuat)
    {
        if(obj==null)
        {
            obj=new XuatChuongGUI(lsHeoXuat);
        }
        return obj;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbHeoXuat = new javax.swing.JTable();
        lbXuatChuongGUI = new javax.swing.JLabel();
        lbTenKhachHang = new javax.swing.JLabel();
        lbMaKhachHang = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbNgayLap = new javax.swing.JLabel();
        lbDonGia = new javax.swing.JLabel();
        lbNguoiLap = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        txtTenKhachHang = new javax.swing.JTextField();
        cbMaKhachHang = new javax.swing.JComboBox<>();
        txtDonGia = new javax.swing.JTextField();
        txtNguoiLap = new javax.swing.JTextField();
        dateNgayLap = new com.toedter.calendar.JDateChooser();
        lbTongTien = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lbSoLuong = new javax.swing.JLabel();
        lbCapNhatCanNang = new javax.swing.JLabel();
        lbTongKyXuat = new javax.swing.JLabel();
        lbThemKhachHang = new javax.swing.JLabel();
        lbDataSoLuong = new javax.swing.JLabel();
        lbDataTongKyXuat = new javax.swing.JLabel();
        lbDataTongTien = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tbHeoXuat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbHeoXuat.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbHeoXuat.getTableHeader().setReorderingAllowed(false);
        tbHeoXuat.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                tbHeoXuatInputMethodTextChanged(evt);
            }
        });
        tbHeoXuat.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tbHeoXuatPropertyChange(evt);
            }
        });
        tbHeoXuat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbHeoXuatKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tbHeoXuatKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(tbHeoXuat);

        lbXuatChuongGUI.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbXuatChuongGUI.setText("LẬP HÓA ĐƠN XUẤT CHUỒNG");
        lbXuatChuongGUI.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbXuatChuongGUI.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbXuatChuongGUI.setName(""); // NOI18N

        lbTenKhachHang.setText("Tên khách hàng");

        lbMaKhachHang.setText("Mã khách hàng");

        jLabel4.setText("SĐT");

        lbNgayLap.setText("Ngày lập");
        lbNgayLap.setPreferredSize(new java.awt.Dimension(76, 14));

        lbDonGia.setText("Đơn giá (VND)");
        lbDonGia.setMaximumSize(new java.awt.Dimension(14, 14));
        lbDonGia.setPreferredSize(new java.awt.Dimension(76, 14));

        lbNguoiLap.setText("Người lập");

        txtSDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSDTActionPerformed(evt);
            }
        });

        cbMaKhachHang.setToolTipText("");
        cbMaKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbMaKhachHangMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cbMaKhachHangMousePressed(evt);
            }
        });
        cbMaKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMaKhachHangActionPerformed(evt);
            }
        });

        txtDonGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDonGiaActionPerformed(evt);
            }
        });

        dateNgayLap.setDateFormatString("yyyy-MM-dd");

        lbTongTien.setText("TỔNG TIỀN (VND)");

        jButton1.setText("jButton1");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        lbSoLuong.setText("SỐ LƯỢNG (Con)");

        lbCapNhatCanNang.setBackground(new java.awt.Color(0, 153, 120));
        lbCapNhatCanNang.setText("Cập nhật Cân");
        lbCapNhatCanNang.setOpaque(true);
        lbCapNhatCanNang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbCapNhatCanNangMouseClicked(evt);
            }
        });

        lbTongKyXuat.setText("TỔNG KÝ XUẤT (KG)");

        lbThemKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Item/plus (1).png"))); // NOI18N
        lbThemKhachHang.setOpaque(true);
        lbThemKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbThemKhachHangMouseClicked(evt);
            }
        });

        lbDataSoLuong.setText("jLabel1");

        lbDataTongKyXuat.setText("jLabel2");

        lbDataTongTien.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(65, 65, 65)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lbNguoiLap, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lbMaKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(cbMaKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lbThemKhachHang)
                                    .addGap(113, 113, 113))
                                .addComponent(lbDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNguoiLap, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(9, 9, 9))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(17, 17, 17)
                            .addComponent(lbCapNhatCanNang)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbXuatChuongGUI, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbTenKhachHang)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtTenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(63, 63, 63)
                                .addComponent(lbNgayLap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(dateNgayLap, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lbTongTien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbTongKyXuat, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbDataTongTien, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                    .addComponent(lbDataTongKyXuat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbDataSoLuong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addGap(55, 55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lbXuatChuongGUI, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lbNgayLap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(lbMaKhachHang))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(dateNgayLap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cbMaKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(15, 15, 15))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbThemKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTenKhachHang)
                            .addComponent(txtTenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbNguoiLap)
                            .addComponent(txtNguoiLap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(lbDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(lbCapNhatCanNang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDataSoLuong))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTongKyXuat)
                    .addComponent(lbDataTongKyXuat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTongTien)
                    .addComponent(lbDataTongTien))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(16, 16, 16))
        );

        lbXuatChuongGUI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbXuatChuongGUI.getAccessibleContext().setAccessibleDescription("");
        lbCapNhatCanNang.getAccessibleContext().setAccessibleName("lbCapNhatKg");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSDTActionPerformed

    private void cbMaKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMaKhachHangActionPerformed
            
        if (cbMaKhachHang.getSelectedIndex() == 0) {
            txtTenKhachHang.setText(null);
            txtSDT.setText(null);
        }
        else {
            KhachHangBUS bus = new KhachHangBUS();
             ResultSet rs = bus.getByID(cbMaKhachHang.getSelectedItem().toString());
       
            try {
                while(rs.next()) {
                   txtTenKhachHang.setText(rs.getString("HoTen"));
                   txtSDT.setText(rs.getString("Sdt"));
                }

            } catch (SQLException ex) {
                Logger.getLogger(XuatChuongGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        

    }//GEN-LAST:event_cbMaKhachHangActionPerformed

    private void cbMaKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbMaKhachHangMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_cbMaKhachHangMouseClicked

    private void cbMaKhachHangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbMaKhachHangMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cbMaKhachHangMousePressed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2MouseClicked
    private void tinhTongTien() {
        int TongKg = 0;
        int SoLuong = 0;
        for (int i = 0; i < tbHeoXuat.getRowCount(); i++) {
            TongKg += Integer.parseInt(tbHeoXuat.getValueAt(i,4).toString());
            SoLuong++;
        }
        lbDataTongKyXuat.setText(String.valueOf(TongKg));
        int TongTien = TongKg*DonGia;
        lbDataTongTien.setText(String.valueOf(TongTien));    
        lbDataSoLuong.setText(String.valueOf(SoLuong));
    }
    private void txtDonGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDonGiaActionPerformed
        // TODO add your handling code here:
        try {
            DonGia = Integer.parseInt(txtDonGia.getText());
            tinhTongTien();
            
        } catch (NumberFormatException nfe) {
            txtDonGia.setText("0");
            DonGia = 0;
            JOptionPane.showMessageDialog(this, "Đơn gia phải là số!","Cảnh báo",
            JOptionPane.WARNING_MESSAGE);
         }
   
        
    }//GEN-LAST:event_txtDonGiaActionPerformed

    private void lbCapNhatCanNangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCapNhatCanNangMouseClicked
        // TODO add your handling code here:
        tinhTongTien();
        
    }//GEN-LAST:event_lbCapNhatCanNangMouseClicked

    private void tbHeoXuatInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_tbHeoXuatInputMethodTextChanged
        // TODO add your handling code here
        
    }//GEN-LAST:event_tbHeoXuatInputMethodTextChanged

    private void tbHeoXuatPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tbHeoXuatPropertyChange
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tbHeoXuatPropertyChange

    private void lbThemKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbThemKhachHangMouseClicked
        // TODO add your handling code here:
        ThemKhachHangGUI themKH = new ThemKhachHangGUI();
        themKH.setVisible(true);
    }//GEN-LAST:event_lbThemKhachHangMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        tinhTongTien();
        String dNgayLap;
        dNgayLap = ((JTextField)dateNgayLap.getDateEditor().getUiComponent()).getText();
        HoaDonBUS busHD = new HoaDonBUS();
        CTHoaDonBUS busCTHD = new CTHoaDonBUS();
        if ((cbMaKhachHang.getSelectedItem().equals("") == false) || 
                    (txtNguoiLap.getText().equals("") == false))
        {
            List<String> listMaHeo = new LinkedList();
            for (int i = 0; i < tbHeoXuat.getRowCount(); i++) 
            {
                 listMaHeo.add((String) tbHeoXuat.getModel().getValueAt(i,0));
            }
            try {
                if ((busHD.insertHoaDon(txtNguoiLap.getText(), Integer.parseInt(lbDataSoLuong.getText()),
                        cbMaKhachHang.getSelectedItem().toString(), dNgayLap) == true) &&
                    (busCTHD.insertCTHD(busHD.getIDhasInserted(), listMaHeo, Double.parseDouble(txtDonGia.getText()))) == true    
                    )
                {
                      JOptionPane.showMessageDialog(this, "Nhập hóa đơn thành công","Thông báo",JOptionPane.DEFAULT_OPTION);
                      this.dispose();  
                }
                         
            }
            catch (HeadlessException | NumberFormatException | SQLException e) 
            {
                JOptionPane.showMessageDialog(this, "Không thể nhập hóa đơn","Cảnh báo",
                JOptionPane.WARNING_MESSAGE);
            }
        } 
              
        // private javax.swing.JTextField txtDonGia;
        // private javax.swing.JTextField txtNguoiLap;
        // private javax.swing.JComboBox<String> cbMaKhachHang;
        // private com.toedter.calendar.JDateChooser dateNgayLap;
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tbHeoXuatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbHeoXuatKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tbHeoXuatKeyTyped

    private void tbHeoXuatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbHeoXuatKeyReleased
        // TODO add your handling code here:
        tinhTongTien();
    }//GEN-LAST:event_tbHeoXuatKeyReleased
    private void bindingComboKhachHang() {
        
        KhachHangBUS bus = new KhachHangBUS();
        ResultSet rs = bus.getAll();
        cbMaKhachHang.insertItemAt("", 0);
        try
        {
            while(rs.next())
            {
                cbMaKhachHang.addItem(rs.getString("MaKhachHang"));

            }
        }
        catch(SQLException exc)
        {
            System.out.println("Loi khi showCommboBox KhachHang "+ exc);
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(XuatChuongGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(XuatChuongGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(XuatChuongGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(XuatChuongGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new XuatChuongGUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbMaKhachHang;
    private com.toedter.calendar.JDateChooser dateNgayLap;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbCapNhatCanNang;
    private javax.swing.JLabel lbDataSoLuong;
    private javax.swing.JLabel lbDataTongKyXuat;
    private javax.swing.JLabel lbDataTongTien;
    private javax.swing.JLabel lbDonGia;
    private javax.swing.JLabel lbMaKhachHang;
    private javax.swing.JLabel lbNgayLap;
    private javax.swing.JLabel lbNguoiLap;
    private javax.swing.JLabel lbSoLuong;
    private javax.swing.JLabel lbTenKhachHang;
    private javax.swing.JLabel lbThemKhachHang;
    private javax.swing.JLabel lbTongKyXuat;
    private javax.swing.JLabel lbTongTien;
    private javax.swing.JLabel lbXuatChuongGUI;
    public javax.swing.JTable tbHeoXuat;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtNguoiLap;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTenKhachHang;
    // End of variables declaration//GEN-END:variables
    
    static class setVisible {

        public setVisible(boolean b) {
        }
    }

    @SuppressWarnings("empty-statement")
    public XuatChuongGUI(ArrayList<HeoELE> lsHeoXuat) {
        
        initComponents();
        txtDonGia.setText("0");
        Calendar cal = new GregorianCalendar();
        dateNgayLap.setDate(cal.getTime());
        DonGia = Integer.parseInt(txtDonGia.getText());
        model = (DefaultTableModel) this.tbHeoXuat.getModel();
        model.addColumn("Mã heo");
        model.addColumn("Tình trạng");
        model.addColumn("Xuất xứ");
        model.addColumn("Giới tính");
        model.addColumn("Cân nặng xuất (Kg)");
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        for(int i=0;i<lsHeoXuat.size();i++)
        {
            Vector vector=new Vector();
            //Mỗi dòng sẽ lấy các giá trị tương ứng với model.addColumn("");
            vector.add(lsHeoXuat.get(i).getMaHeo());
            vector.add(lsHeoXuat.get(i).getTinhTrang());
            vector.add(lsHeoXuat.get(i).getXuatXu());
            vector.add(lsHeoXuat.get(i).getsGioiTinh());
            vector.add(0);
            model.addRow(vector);
        }
        bindingComboKhachHang();
        tinhTongTien();
     }
}
